print("##############################")
print("#                            #")
print("# Jovan Gilbert Natamasindah #")
print("#       2310817310002        #")
print("#                            #")
print("##############################")